version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: socventas-db
    restart: always
    environment:
      MYSQL_DATABASE: ventas_seroficom_db
      MYSQL_ROOT_PASSWORD: "Seroficom_Secure_2025!"
    ports:
      - "5073:3306"
    volumes:
      - socventas_db_data:/var/lib/mysql
    networks:
      - apps-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: socventas-phpmyadmin
    restart: always
    ports:
      - "5072:80"
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
      # Configuraci√≥n avanzada para forzar cookies en HTTP
      PMA_CONFIG_PARAMETERS: |
        $cfg['CookieSecure'] = false;
        $cfg['CheckConfigurationPermissions'] = false;
        $cfg['LoginCookieValidity'] = 1440;
        $cfg['SessionSavePath'] = '/tmp';
    depends_on:
      - db
    networks:
      - apps-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socventas-backend
    restart: always
    ports:
      - "5070:3100"
    env_file:
      - ./backend/.env.production
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: "Seroficom_Secure_2025!"
      DB_NAME: ventas_seroficom_db
    depends_on:
      - db
    networks:
      - apps-network

networks:
  apps-network:
    external: true

volumes:
  socventas_db_data: