version: '3.8'

services:
  db-seroficom:
    image: mysql:8.0
    container_name: socventas-db
    restart: always
    environment:
      MYSQL_DATABASE: ventas_seroficom_db
      MYSQL_ROOT_PASSWORD: "Seroficom_Secure_2025!"
    ports:
      - "5073:3306"
    volumes:
      # PROTECCIÓN DE BASE DE DATOS: Los datos persisten aunque borres el contenedor
      - socventas_vol_final_definitivo:/var/lib/mysql
    networks:
      - apps-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: socventas-phpmyadmin
    restart: always
    ports:
      - "5072:80"
    environment:
      PMA_HOST: db-seroficom
      PMA_ARBITRARY: 1
      PMA_CONFIG_PARAMETERS: |
        $cfg['CookieSecure'] = false;
    depends_on:
      - db-seroficom
    networks:
      - apps-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socventas-backend
    restart: always
    ports:
      - "5070:3150" # Puerto que escucha el Proxy Inverso
    environment:
      - DB_HOST=db-seroficom
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Seroficom_Secure_2025!
      - DB_NAME=ventas_seroficom_db
      - NODE_ENV=production
    volumes:
      # PROTECCIÓN DE ARCHIVOS: Mapea la carpeta real del servidor a la del contenedor
      # Esto evita que 'public/contratos' se borre al actualizar la imagen
      - ./backend/public/contratos:/app/dist/public/contratos
      - ./backend/public/assets:/app/dist/public/assets
    depends_on:
      - db-seroficom
    networks:
      - apps-network

networks:
  apps-network:
    external: true

volumes:
  # Volumen persistente para MySQL
  socventas_vol_final_definitivo:
    external: false