version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_ventas
    restart: always
    environment:
      # Portainer leerá estos valores de la pestaña "Environment variables"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - apps-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_ventas
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - apps-network

  app:
    # Si usas Git en Portainer, asegúrate de poner la ruta relativa al Dockerfile
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_api_ventas
    restart: always
    ports:
      - "3100:3100"
    # IMPORTANTE: En Portainer, las variables se pasan en la pestaña de abajo
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
    networks:
      - apps-network

networks:
  apps-network:
    external: true

volumes:
  db_data: