version: '3.8'

services:
  db-socventas:
    image: mysql:8.0
    container_name: socventas-db
    restart: always
    environment:
      MYSQL_DATABASE: ventas_seroficom_db
      MYSQL_ROOT_PASSWORD: "Seroficom_Secure_2025!"
    ports:
      - "5073:3306"
    volumes:
      - socventas_db_final:/var/lib/mysql
    networks:
      - apps-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: socventas-phpmyadmin
    restart: always
    ports:
      - "5072:80"
    environment:
      # Debe coincidir con el nombre del servicio de arriba
      PMA_HOST: db-socventas
      PMA_ARBITRARY: 1
      PMA_CONFIG_PARAMETERS: |
        $cfg['CookieSecure'] = false;
        $cfg['LoginCookieValidity'] = 3600;
    depends_on:
      - db-socventas
    networks:
      - apps-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socventas-backend
    restart: always
    ports:
      - "5070:3100"
    environment:
      # FORZAMOS LAS VARIABLES AQU√ç (Esto ignora el .env defectuoso)
      DB_HOST: db-socventas
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: "Seroficom_Secure_2025!"
      DB_NAME: ventas_seroficom_db
      NODE_ENV: production
    depends_on:
      - db-socventas
    networks:
      - apps-network

networks:
  apps-network:
    external: true

volumes:
  socventas_db_final: